#!/usr/bin/env sh

npx typesafe-i18n --no-watch
git add src/lib/i18n/i18n-types.ts src/lib/i18n/i18n-util.ts src/lib/i18n/i18n-util.async.ts src/lib/i18n/i18n-util.sync.ts src/lib/i18n/i18n-svelte.ts

# Formate tous les fichiers stagés avec Prettier avant le commit
FILES=$(git diff --cached --name-only --diff-filter=ACMR)
[ -z "$FILES" ] || npx prettier --write --ignore-unknown $FILES
[ -z "$FILES" ] || git add $FILES


npm run verify

