export type WhisperLanguageOption = {
	code: string;
	label: string;
};

/** Languages accepted by multilingual Whisper models. */
export const WHISPER_LANGUAGE_OPTIONS: readonly WhisperLanguageOption[] = [
	{ code: 'auto', label: 'Automatic detection' },
	{ code: 'af', label: 'Afrikaans' },
	{ code: 'sq', label: 'Albanian' },
	{ code: 'am', label: 'Amharic' },
	{ code: 'ar', label: 'Arabic' },
	{ code: 'hy', label: 'Armenian' },
	{ code: 'as', label: 'Assamese' },
	{ code: 'az', label: 'Azerbaijani' },
	{ code: 'ba', label: 'Bashkir' },
	{ code: 'eu', label: 'Basque' },
	{ code: 'be', label: 'Belarusian' },
	{ code: 'bn', label: 'Bengali' },
	{ code: 'bs', label: 'Bosnian' },
	{ code: 'br', label: 'Breton' },
	{ code: 'bg', label: 'Bulgarian' },
	{ code: 'my', label: 'Burmese' },
	{ code: 'ca', label: 'Catalan' },
	{ code: 'zh', label: 'Chinese' },
	{ code: 'hr', label: 'Croatian' },
	{ code: 'cs', label: 'Czech' },
	{ code: 'da', label: 'Danish' },
	{ code: 'nl', label: 'Dutch' },
	{ code: 'en', label: 'English' },
	{ code: 'et', label: 'Estonian' },
	{ code: 'fo', label: 'Faroese' },
	{ code: 'fi', label: 'Finnish' },
	{ code: 'fr', label: 'French' },
	{ code: 'gl', label: 'Galician' },
	{ code: 'ka', label: 'Georgian' },
	{ code: 'de', label: 'German' },
	{ code: 'el', label: 'Greek' },
	{ code: 'gu', label: 'Gujarati' },
	{ code: 'ht', label: 'Haitian Creole' },
	{ code: 'ha', label: 'Hausa' },
	{ code: 'haw', label: 'Hawaiian' },
	{ code: 'he', label: 'Hebrew' },
	{ code: 'hi', label: 'Hindi' },
	{ code: 'hu', label: 'Hungarian' },
	{ code: 'is', label: 'Icelandic' },
	{ code: 'id', label: 'Indonesian' },
	{ code: 'it', label: 'Italian' },
	{ code: 'ja', label: 'Japanese' },
	{ code: 'jw', label: 'Javanese' },
	{ code: 'kn', label: 'Kannada' },
	{ code: 'kk', label: 'Kazakh' },
	{ code: 'km', label: 'Khmer' },
	{ code: 'ko', label: 'Korean' },
	{ code: 'lo', label: 'Lao' },
	{ code: 'la', label: 'Latin' },
	{ code: 'lv', label: 'Latvian' },
	{ code: 'ln', label: 'Lingala' },
	{ code: 'lt', label: 'Lithuanian' },
	{ code: 'lb', label: 'Luxembourgish' },
	{ code: 'mk', label: 'Macedonian' },
	{ code: 'mg', label: 'Malagasy' },
	{ code: 'ms', label: 'Malay' },
	{ code: 'ml', label: 'Malayalam' },
	{ code: 'mt', label: 'Maltese' },
	{ code: 'mi', label: 'Maori' },
	{ code: 'mr', label: 'Marathi' },
	{ code: 'mn', label: 'Mongolian' },
	{ code: 'ne', label: 'Nepali' },
	{ code: 'no', label: 'Norwegian' },
	{ code: 'nn', label: 'Nynorsk' },
	{ code: 'oc', label: 'Occitan' },
	{ code: 'ps', label: 'Pashto' },
	{ code: 'fa', label: 'Persian' },
	{ code: 'pl', label: 'Polish' },
	{ code: 'pt', label: 'Portuguese' },
	{ code: 'pa', label: 'Punjabi' },
	{ code: 'ro', label: 'Romanian' },
	{ code: 'ru', label: 'Russian' },
	{ code: 'sa', label: 'Sanskrit' },
	{ code: 'sr', label: 'Serbian' },
	{ code: 'sn', label: 'Shona' },
	{ code: 'sd', label: 'Sindhi' },
	{ code: 'si', label: 'Sinhala' },
	{ code: 'sk', label: 'Slovak' },
	{ code: 'sl', label: 'Slovenian' },
	{ code: 'so', label: 'Somali' },
	{ code: 'es', label: 'Spanish' },
	{ code: 'su', label: 'Sundanese' },
	{ code: 'sw', label: 'Swahili' },
	{ code: 'sv', label: 'Swedish' },
	{ code: 'tl', label: 'Tagalog' },
	{ code: 'tg', label: 'Tajik' },
	{ code: 'ta', label: 'Tamil' },
	{ code: 'tt', label: 'Tatar' },
	{ code: 'te', label: 'Telugu' },
	{ code: 'th', label: 'Thai' },
	{ code: 'bo', label: 'Tibetan' },
	{ code: 'tr', label: 'Turkish' },
	{ code: 'tk', label: 'Turkmen' },
	{ code: 'uk', label: 'Ukrainian' },
	{ code: 'ur', label: 'Urdu' },
	{ code: 'uz', label: 'Uzbek' },
	{ code: 'vi', label: 'Vietnamese' },
	{ code: 'cy', label: 'Welsh' },
	{ code: 'yi', label: 'Yiddish' },
	{ code: 'yo', label: 'Yoruba' },
	{ code: 'yue', label: 'Cantonese' }
];

export function getWhisperLanguageLabel(code: string): string {
	return (
		WHISPER_LANGUAGE_OPTIONS.find((option) => option.code === code)?.label ?? code.toUpperCase()
	);
}
