name: Build macOS App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      # Installe 7zip pour pouvoir extraire les .7z
      - name: Install p7zip
        run: brew install p7zip
      # Télécharger le build essentials et n’extraire que ffprobe.exe
      - name: Download and extract ffprobe.exe
        run: |
          mkdir -p src-tauri
          curl -L -o ffmpeg.7z https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z
          # -e pour extraire sans structure de dossier, filtrer le chemin vers bin\ffprobe.exe
          7z e ffmpeg.7z "*\bin\ffprobe.exe" -o src-tauri -y
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Patch time crate
        working-directory: src-tauri
        run: cargo update -p time --precise 0.3.35
      - name: Install app dependencies
        run: npm install
      - name: Build the app
        run: npm run tauri build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: src-tauri/target/release/bundle
